### ISSUE TITLE
Social share preview for DRep ID

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/drep-id#2]
As a user when I share my DRep URL, it should show a properly rendered social share preview.

Title: DRep Name
Description: Objectives (limited 80 characters ?? pls verify)
Image: Image of the DRep if included in the metadata, otherwise rendering of the DRep Name in a big letters
Link: Link to DRep ID profile page.

# Acceptance criteria:
- Open graph tags are properly set
- Preview works well on the following platforms:
  - Facebook
  - X
  - Discord
  - Telegram

**Comment by reeshavacharya** [comment]
- Title: DRep's given name when available otherwise DRep bech32 id in case the DRep is retired
- Description: recommended length is 110 characters according to social preview. description length is variable across platforms. so it has been limited to the length of the dRep id default description. Description  will be either DRep's objectives or motivation or qualification if available. Otherwise, it will be the default description. 
- Image of the DRep is not implemented yet. 
- DRep's name in big letters will be displayed when shared.  
- Like will be to DRepId profile page

**Comment by reeshavacharya** [comment]
> **Update**
> - Image of the DRep will be displayed in social share preview if available
